services:
  coreai-mcu-frontend:
    build:
      context: ./coreai-mcu-frontend
      target: development
    image: coreai-mcu-frontend
    container_name: coreai-mcu-frontend
    ports:
      - "3000:3000"
      - "9229:9229"
    environment:
      MESSAGE_QUEUE_HOST: ${MESSAGE_QUEUE_HOST}
      MESSAGE_QUEUE_USER: ${MESSAGE_QUEUE_USER}
      MESSAGE_QUEUE_PASSWORD: ${MESSAGE_QUEUE_PASSWORD}
      GENERATION_REQUEST_TOPIC: ${GENERATION_REQUEST_TOPIC:-coreai-mcu-generation-request}${MESSAGE_QUEUE_SUFFIX}
      KNOWLEDGE_INGESTION_TOPIC: ${KNOWLEDGE_INGESTION_TOPIC:-coreai-mcu-knowledge-ingestion}${MESSAGE_QUEUE_SUFFIX}
      RESPONSE_PROCESSING_QUEUE_ADDRESS: ${RESPONSE_PROCESSING_QUEUE_ADDRESS:-coreai-mcu-generation-response}${MESSAGE_QUEUE_SUFFIX}
      DOCUMENTS_API_BASE_URL: ${DOCUMENTS_API_BASE_URL:-coreai-mcu-documents}
      RESPONSES_API_BASE_URL: ${RESPONSES_API_BASE_URL:-coreai-mcu-responses}

  coreai-mcu-documents:
    build:
      context: ./coreai-mcu-documents
      target: development
    image: coreai-mcu-documents
    container_name: coreai-mcu-documents
    ports:
      - "3001:3000"
      - "9230:9229"
    environment:
      AZURE_STORAGE_USE_CONNECTION_STRING: ${AZURE_STORAGE_USE_CONNECTION_STRING:-true}
      AZURE_STORAGE_CONNECTION_STRING: ${AZURE_STORAGE_CONNECTION_STRING}
      AZURE_STORAGE_ACCOUNT: ${AZURE_STORAGE_ACCOUNT}

  coreai-mcu-generation-oai:
    build:
      context: ./coreai-mcu-generation-oai
      target: development
    image: coreai-mcu-generation-oai
    container_name: coreai-mcu-generation-oai
    ports:
      - "3002:3000"
      - "9231:9229"
    environment:
      POSTGRES_DB: coreai-mcu-knowledge-pgv
      POSTGRES_HOST: ${POSTGRES_HOST:-coreai-mcu-knowledge-pgv}
      POSTGRES_PORT: 5432
      POSTGRES_SCHEMA_NAME: ${POSTGRES_SCHEMA_NAME:-public}
      POSTGRES_USERNAME: ${POSTGRES_SCHEMA_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_SCHEMA_PASSWORD:-ppp}
      MESSAGE_QUEUE_HOST: ${MESSAGE_QUEUE_HOST}
      MESSAGE_QUEUE_USER: ${MESSAGE_QUEUE_USER}
      MESSAGE_QUEUE_PASSWORD: ${MESSAGE_QUEUE_PASSWORD}
      GENERATION_REQUEST_OAI_SUBSCRIPTION: ${GENERATION_REQUEST_OAI_SUBSCRIPTION:-coreai-mcu-generation-oai}
      GENERATION_REQUEST_TOPIC: ${GENERATION_REQUEST_TOPIC:-coreai-mcu-generation-request}${MESSAGE_QUEUE_SUFFIX}
      AZURE_STORAGE_USE_CONNECTION_STRING: ${AZURE_STORAGE_USE_CONNECTION_STRING}
      AZURE_STORAGE_CONNECTION_STRING: ${AZURE_STORAGE_CONNECTION_STRING}
      AZURE_STORAGE_ACCOUNT: ${AZURE_STORAGE_ACCOUNT}

  coreai-mcu-knowledge-pgv:
    build:
      context: ./coreai-mcu-knowledge-pgv
      target: development
    image: coreai-mcu-knowledge-pgv
    container_name: coreai-mcu-knowledge-pgv
    ports:
      - "3003:3000"
      - "9232:9229"
    environment:
      POSTGRES_DB: coreai-mcu-knowledge-pgv
      POSTGRES_HOST: ${POSTGRES_HOST:-coreai-mcu-knowledge-pgv}
      POSTGRES_PORT: 5432
      POSTGRES_SCHEMA_NAME: ${POSTGRES_SCHEMA_NAME:-public}
      POSTGRES_USERNAME: ${POSTGRES_SCHEMA_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_SCHEMA_PASSWORD:-ppp}
      MESSAGE_QUEUE_HOST: ${MESSAGE_QUEUE_HOST}
      MESSAGE_QUEUE_USER: ${MESSAGE_QUEUE_USER}
      MESSAGE_QUEUE_PASSWORD: ${MESSAGE_QUEUE_PASSWORD}
      KNOWLEDGE_INGESTION_PGV_SUBSCRIPTION: ${KNOWLEDGE_INGESTION_PGV_SUBSCRIPTION:-coreai-mcu-knowledge-pgv}
      KNOWLEDGE_INGESTION_TOPIC: ${KNOWLEDGE_INGESTION_TOPIC:-coreai-mcu-knowledge-ingestion}${MESSAGE_QUEUE_SUFFIX}
      AZURE_STORAGE_USE_CONNECTION_STRING: ${AZURE_STORAGE_USE_CONNECTION_STRING}
      AZURE_STORAGE_CONNECTION_STRING: ${AZURE_STORAGE_CONNECTION_STRING}
      AZURE_STORAGE_ACCOUNT: ${AZURE_STORAGE_ACCOUNT}

  coreai-mcu-responses:
    build:
      context: ./coreai-mcu-responses
      target: development
    image: coreai-mcu-responses
    container_name: coreai-mcu-responses
    ports:
      - "3004:3000"
      - "9233:9229"
    environment:
      MESSAGE_QUEUE_HOST: ${MESSAGE_QUEUE_HOST}
      MESSAGE_QUEUE_USER: ${MESSAGE_QUEUE_USER}
      MESSAGE_QUEUE_PASSWORD: ${MESSAGE_QUEUE_PASSWORD}
      RESPONSE_PROCESSING_QUEUE_ADDRESS: ${RESPONSE_PROCESSING_QUEUE_ADDRESS:-coreai-mcu-generation-response}${MESSAGE_QUEUE_SUFFIX}
      AZURE_STORAGE_USE_CONNECTION_STRING: ${AZURE_STORAGE_USE_CONNECTION_STRING}
      AZURE_STORAGE_CONNECTION_STRING: ${AZURE_STORAGE_CONNECTION_STRING}
      AZURE_STORAGE_ACCOUNT: ${AZURE_STORAGE_ACCOUNT}

  coreai-mcu-postgres:
    build:
      context: .
      dockerfile: ./coreai-mcu-knowledge-pgv/postgres/Dockerfile
    image: coreai-mcu-knowledge-pgv-postgres
    environment:
      POSTGRES_DB: coreai-mcu-knowledge
      POSTGRES_PASSWORD: ppp
      POSTGRES_USERNAME: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  coreai-mcu-azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - "10000:10000"
      - "10002:10002"
    volumes:
      - azurite_data:/data

volumes:
  azurite_data:
  postgres_data:
