services:
  coreai-mcu-frontend:
    build:
      context: ./coreai-mcu-frontend
      target: development
    image: coreai-mcu-frontend
    container_name: coreai-mcu-frontend
    ports:
      - "3000:3000"
      - "9229:9229"
    environment:
      MESSAGE_QUEUE_HOST: ${MESSAGE_QUEUE_HOST}
      MESSAGE_QUEUE_USER: ${MESSAGE_QUEUE_USER}
      MESSAGE_QUEUE_PASSWORD: ${MESSAGE_QUEUE_PASSWORD}
      AUTHENTICATION_ENABLED: ${AUTHENTICATION_ENABLED:-false}
      AZUREID_CLIENT_SECRET: ${AZUREID_CLIENT_SECRET}
      AZUREID_CLIENT_ID: ${AZUREID_CLIENT_ID}
      AZUREID_TENANT_ID: ${AZUREID_TENANT_ID}
      COOKIE_PASSWORD: who-likes-cookies-i-like-cookies-everybody-likes-cookies
      GENERATION_REQUEST_TOPIC: ${GENERATION_REQUEST_TOPIC:-coreai-mcu-generate}${MESSAGE_QUEUE_SUFFIX}
      TRIAGE_REQUEST_TOPIC: ${TRIAGE_REQUEST_TOPIC:-coreai-mcu-triage}${MESSAGE_QUEUE_SUFFIX}
      KNOWLEDGE_INGESTION_TOPIC: ${KNOWLEDGE_INGESTION_TOPIC:-coreai-mcu-knowledge-ingest}${MESSAGE_QUEUE_SUFFIX}
      EVENTS_TOPIC_ADDRESS: ${EVENT_TOPIC:-coreai-mcu-events}${MESSAGE_QUEUE_SUFFIX}
      EVENTS_SUBSCRIPTION: ${EVENT_SUBSCRIPTION:-coreai-mcu-frontend}
      DOCUMENTS_API_BASE_URL: ${DOCUMENTS_API_BASE_URL:-coreai-mcu-documents}
      KNOWLEDGE_API_BASE_URL: ${KNOWLEDGE_API_BASE_URL:-coreai-mcu-knowledge}
      RESPONSES_API_BASE_URL: ${RESPONSES_API_BASE_URL:-coreai-mcu-responses}
      PROMPTS_API_BASE_URL: ${PROMPTS_API_BASE_URL:-coreai-mcu-prompts}
      NOTIFY_API_KEY: ${NOTIFY_API_KEY}
      NOTIFY_TEMPLATE_ID_CORRESPONDENCE: ${NOTIFY_TEMPLATE_ID_CORRESPONDENCE}
      CARBON_COPY_EMAIL_ADDRESS: ${CARBON_COPY_EMAIL_ADDRESS}

  coreai-mcu-documents:
    build:
      context: ./coreai-mcu-documents
      target: development
    image: coreai-mcu-documents
    container_name: coreai-mcu-documents
    ports:
      - "3001:3000"
      - "9230:9229"
    environment:
      AZURE_STORAGE_USE_CONNECTION_STRING: ${AZURE_STORAGE_USE_CONNECTION_STRING:-true}
      AZURE_STORAGE_CONNECTION_STRING: ${AZURE_STORAGE_CONNECTION_STRING}
      AZURE_STORAGE_ACCOUNT: ${AZURE_STORAGE_ACCOUNT}

  coreai-mcu-generation-oai:
    build:
      context: ./coreai-mcu-generation-oai
      target: development
    image: coreai-mcu-generation-oai
    container_name: coreai-mcu-generation-oai
    ports:
      - "3002:3000"
      - "9231:9229"
    environment:
      POSTGRES_DB: coreai-mcu-knowledge-pgv
      POSTGRES_HOST: ${POSTGRES_HOST:-host.docker.internal}
      POSTGRES_PORT: 5432
      POSTGRES_SCHEMA_NAME: ${POSTGRES_SCHEMA_NAME:-public}
      POSTGRES_USERNAME: ${POSTGRES_SCHEMA_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_SCHEMA_PASSWORD:-ppp}
      MESSAGE_QUEUE_HOST: ${MESSAGE_QUEUE_HOST}
      MESSAGE_QUEUE_USER: ${MESSAGE_QUEUE_USER}
      MESSAGE_QUEUE_PASSWORD: ${MESSAGE_QUEUE_PASSWORD}
      GENERATION_REQUEST_OAI_SUBSCRIPTION: ${GENERATION_REQUEST_OAI_SUBSCRIPTION:-coreai-mcu-generation-oai}
      AZURE_OPENAI_ENABLED: ${AZURE_OPENAI_ENABLED:-true}
      GENERATION_REQUEST_TOPIC: ${GENERATION_REQUEST_TOPIC:-coreai-mcu-generate}${MESSAGE_QUEUE_SUFFIX}
      SUMMARY_REQUEST_TOPIC: ${SUMMARY_REQUEST_TOPIC:-coreai-mcu-triage}${MESSAGE_QUEUE_SUFFIX}
      RESPONSE_PROCESSING_QUEUE_ADDRESS: ${RESPONSE_PROCESSING_QUEUE_ADDRESS:-coreai-mcu-response}${MESSAGE_QUEUE_SUFFIX}
      AZURE_STORAGE_USE_CONNECTION_STRING: ${AZURE_STORAGE_USE_CONNECTION_STRING}
      AZURE_STORAGE_CONNECTION_STRING: ${AZURE_STORAGE_CONNECTION_STRING}
      AZURE_STORAGE_ACCOUNT: ${AZURE_STORAGE_ACCOUNT}
      AZURE_OPENAI_INSTANCE_NAME: ${AZURE_OPENAI_INSTANCE_NAME:-test}
      AZURE_OPENAI_KEY: ${AZURE_OPENAI_KEY:-test}
      AZURE_OPENAI_API_VERSION: ${AZURE_OPENAI_API_VERSION:-test}
      EMBEDDING_MODEL_NAME: ${EMBEDDING_MODEL_NAME:-test}
      GENERATION_MODEL_NAME: ${GENERATION_MODEL_NAME:-test}
      DOCUMENTS_API_BASE_URL: ${DOCUMENTS_API_BASE_URL:-coreai-mcu-documents}
      RESPONSES_API_BASE_URL: ${RESPONSES_API_BASE_URL:-coreai-mcu-responses}
      PROMPTS_API_BASE_URL: ${PROMPTS_API_BASE_URL:-coreai-mcu-prompts}
      OLLAMA_BASE_URL: ${OLLAMA_BASE_URL:-http://host.docker.internal:11434}

  coreai-mcu-knowledge-pgv:
    build:
      context: ./coreai-mcu-knowledge-pgv
      target: development
    image: coreai-mcu-knowledge-pgv
    container_name: coreai-mcu-knowledge-pgv
    ports:
      - "3003:3000"
      - "9232:9229"
    environment:
      POSTGRES_DB: coreai-mcu-knowledge-pgv
      POSTGRES_HOST: ${POSTGRES_HOST:-coreai-mcu-postgres}
      POSTGRES_PORT: 5432
      POSTGRES_SCHEMA_NAME: ${POSTGRES_SCHEMA_NAME:-public}
      POSTGRES_USERNAME: ${POSTGRES_SCHEMA_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_SCHEMA_PASSWORD:-ppp}
      MESSAGE_QUEUE_HOST: ${MESSAGE_QUEUE_HOST}
      MESSAGE_QUEUE_USER: ${MESSAGE_QUEUE_USER}
      MESSAGE_QUEUE_PASSWORD: ${MESSAGE_QUEUE_PASSWORD}
      KNOWLEDGE_INGESTION_PGV_SUBSCRIPTION: ${KNOWLEDGE_INGESTION_PGV_SUBSCRIPTION:-coreai-mcu-knowledge-pgv}
      KNOWLEDGE_INGESTION_TOPIC: ${KNOWLEDGE_INGESTION_TOPIC:-coreai-mcu-knowledge-ingest}${MESSAGE_QUEUE_SUFFIX}
      AZURE_STORAGE_USE_CONNECTION_STRING: ${AZURE_STORAGE_USE_CONNECTION_STRING}
      AZURE_STORAGE_CONNECTION_STRING: ${AZURE_STORAGE_CONNECTION_STRING}
      AZURE_STORAGE_ACCOUNT: ${AZURE_STORAGE_ACCOUNT}
      AZURE_OPENAI_INSTANCE_NAME: ${AZURE_OPENAI_INSTANCE_NAME:-test}
      AZURE_OPENAI_KEY: ${AZURE_OPENAI_KEY:-test}
      AZURE_OPENAI_API_VERSION: ${AZURE_OPENAI_API_VERSION:-test}
      EMBEDDING_MODEL_NAME: ${EMBEDDING_MODEL_NAME:-test}

  coreai-mcu-responses:
    build:
      context: ./coreai-mcu-responses
      target: development
    image: coreai-mcu-responses
    container_name: coreai-mcu-responses
    ports:
      - "3004:3000"
      - "9233:9229"
    environment:
      MESSAGE_QUEUE_HOST: ${MESSAGE_QUEUE_HOST}
      MESSAGE_QUEUE_USER: ${MESSAGE_QUEUE_USER}
      MESSAGE_QUEUE_PASSWORD: ${MESSAGE_QUEUE_PASSWORD}
      RESPONSE_PROCESSING_QUEUE_ADDRESS: ${RESPONSE_PROCESSING_QUEUE_ADDRESS:-coreai-mcu-response}${MESSAGE_QUEUE_SUFFIX}
      EVENTS_TOPIC_ADDRESS: ${EVENT_TOPIC:-coreai-mcu-events}${MESSAGE_QUEUE_SUFFIX}
      AZURE_STORAGE_USE_CONNECTION_STRING: ${AZURE_STORAGE_USE_CONNECTION_STRING}
      AZURE_STORAGE_CONNECTION_STRING: ${AZURE_STORAGE_CONNECTION_STRING}
      AZURE_STORAGE_ACCOUNT: ${AZURE_STORAGE_ACCOUNT}

  coreai-mcu-event:
    build:
      context: ./coreai-mcu-event
      target: development
    image: coreai-mcu-event
    container_name: coreai-mcu-event
    ports:
      - "3005:3000"
      - "9234:9229"
    environment:
      MESSAGE_QUEUE_HOST: ${MESSAGE_QUEUE_HOST}
      MESSAGE_QUEUE_USER: ${MESSAGE_QUEUE_USER}
      MESSAGE_QUEUE_PASSWORD: ${MESSAGE_QUEUE_PASSWORD}
      EVENTS_TOPIC_ADDRESS: ${EVENT_TOPIC:-coreai-mcu-events}${MESSAGE_QUEUE_SUFFIX}
      EVENTS_SUBSCRIPTION: ${EVENT_SUBSCRIPTION:-coreai-mcu-event}

  coreai-mcu-prompts:
    build:
      context: ./coreai-mcu-prompts
      target: development
    image: coreai-mcu-prompts
    container_name: coreai-mcu-prompts
    ports:
      - "3006:3000"
      - "9235:9229"
    environment:
      AZURE_STORAGE_USE_CONNECTION_STRING: ${AZURE_STORAGE_USE_CONNECTION_STRING:-true}
      AZURE_STORAGE_CONNECTION_STRING: ${AZURE_STORAGE_CONNECTION_STRING}
      AZURE_STORAGE_ACCOUNT: ${AZURE_STORAGE_ACCOUNT}

  coreai-mcu-persona:
    build:
      context: ./coreai-mcu-persona
      target: development
    image: coreai-mcu-persona
    container_name: coreai-mcu-persona
    ports:
      - "3007:3000"
      - "9236:9229"
    environment:
      AZURE_STORAGE_USE_CONNECTION_STRING: ${AZURE_STORAGE_USE_CONNECTION_STRING:-true}
      AZURE_STORAGE_CONNECTION_STRING: ${AZURE_STORAGE_CONNECTION_STRING}
      AZURE_STORAGE_ACCOUNT: ${AZURE_STORAGE_ACCOUNT}

  coreai-mcu-postgres:
    build:
      context: .
      dockerfile: ./coreai-mcu-knowledge-pgv/postgres/Dockerfile
    image: coreai-mcu-knowledge-pgv-postgres
    environment:
      POSTGRES_DB: coreai-mcu-knowledge
      POSTGRES_PASSWORD: ppp
      POSTGRES_USERNAME: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  coreai-mcu-azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - "10000:10000"
      - "10002:10002"
    volumes:
      - azurite_data:/data

volumes:
  azurite_data:
  postgres_data:
