#!/bin/bash
# Get the Password as parameter. This allows the script to be used when running db migration job in cluster.
SCHEMA_PASSWORD=$1
echo "db update on $POSTGRES_HOST $SCHEMA_NAME as $SCHEMA_USERNAME"

if [ "$LOCAL" = "true" ]; then
  CHANGELOG=db.changelog.local.xml
else
  CHANGELOG=db.changelog.xml
fi

echo "Using changelog $CHANGELOG"

/scripts/postgres-wait && /liquibase/liquibase \
--driver=org.postgresql.Driver \
--changeLogFile=/changelog/$CHANGELOG \
--url=jdbc:postgresql://$POSTGRES_HOST:$POSTGRES_PORT/$POSTGRES_DB \
--username="$SCHEMA_USERNAME" --password="$SCHEMA_PASSWORD" --defaultSchemaName="$SCHEMA_NAME" \
update
